spring:
  main:
    web-application-type: none
interval: 60000
data-url: http://10.82.249.208:9043/api/Business/Group/GetTransGasLineOperatingParameter?lineCode=10001
token: aff39473dfef1f5bdcbe90a52f2a8e45
push-url: http://localhost:6666/gas/add
region: qinghai
unit-map: '{"YL":"MPa","LL":"Nm3/h"}'
